### ISSUE TITLE
[AI Help] Question: Write me a blog page code

### ISSUE THREAD

**Issue by afzaltipu** [mdn/ai-feedback#27]
### What is the issue with the answer?

Afzal Hosen Mandal <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Formatting a biography</title>
    <style>
      body {
        background-color: #fff;
        color: #333;
        font-family: Arial, Helvetica, sans-serif;
        padding: 1em;
        margin: 0;
      }

      h1 {
        color: #375e97;
        font-size: 2em;
        font-family: Georgia, "Times New Roman", Times, serif;
        border-bottom: 1px solid #375e97;
      }

      h2 {
        font-size: 1.5em;
      }

      .job-title {
        color: #999999;
        font-weight: bold;
      }

      a:link,
      a:visited {
        color: #fb6542;
      }

      a:hover {
        text-decoration: none;
      }
    </style>
  </head>

  <body>
    <h1>Jane Doe</h1>
    <div class="job-title">Web Developer</div>
    <p>
      Far far away, behind the word mountains, far from the countries Vokalia
      and Consonantia, there live the blind texts. Separated they live in
      Bookmarksgrove right at the coast of the Semantics, a large language
      ocean.
    </p>

    <p>
      A small river named Duden flows by their place and supplies it with the
      necessary regelialia. It is a paradisematic country, in which roasted
      parts of sentences fly into your mouth.
    </p>

    <h2>Contact information</h2>
    <ul>
      <li>
        Email:
        <a href="mailto:jane@example.com">jane@example.com</a>
      </li>
      <li>
        Web:
        <a href="http://example.com">http://example.com</a>
      </li>
      <li>Tel: 123 45678</li>
    </ul>
  </body>
</html>

### How would you categorize this issue?

- [X] The answer is harmful / unsafe.
- [X] The answer is not correct.
- [X] The answer is not helpful.
- [X] The answer is outdated.

### What did you ask?

1. How to center a div with CSS?
1. Write me a blog page code

### What did AI Help answer?

You can download a starting point file for a blog page from the MDN GitHub repository. The file contains both the HTML and CSS code to create a simple blog page. Here is the link to download the file: [blog page starting point](https://github.com/mdn/css-examples/blob/main/learn/getting-started/biog-download.html).

Once you have downloaded the file, you can open it in your preferred code editor and make modifications as needed. The HTML code includes elements such as headers, content sections, and buttons. The CSS code is included in the head of the document, but you can also move it to a separate file and link to it if you prefer.

Remember that this is just a starting point, and you can customize the code to fit your specific needs. If you get stuck or want to compare your work, you can also refer to the finished example code on GitHub: [finished example code on GitHub](https://github.com/mdn/beginner-html-site-scripted/blob/gh-pages/scripts/main.js).

Feel free to explore and experiment with the code to create your own unique blog page!

### What MDN pages did AI Help consult?

- [Publishing your website](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website)
- [Styling a biography page](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Styling_a_biography_page)
- [Guidelines for writing HTML code examples](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/HTML)
- [JavaScript basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics)
- [Assessment: DIY Django mini blog](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog)

**Comment by caugner** [comment]
Closing as invalid, because the issue template is not properly filled out ("What is the issue with the answer?" is not answered, "How would you categorize this issue?" has all checkboxes ticked).
