### ISSUE TITLE
[AI Help] Question: I think this is also wrong. What do you mean by 'key' parameter is not received 'in this context'? If the object is in an array for example, it will receive the index, right?

### ISSUE THREAD

**Issue by psm384** [mdn/ai-feedback#53]
### What is the issue with the answer?

Curiously, various AIs have trouble answering questions about 'toJson'. The casing is wrong, only 'toJSON' will work :-) but your AI first repeated 'toJson' back to me and then ran with it, only later starting to use 'toJSON' in answers.

Personally i would camel-case even with "JSON", but the point here is the AI at first doesn't spot it, but (interestingly) then repeats back to me 'toJson'.  At which point as a lowly human, i'm not paying attention to the casing any longer.

### How would you categorize this issue?

- [ ] The answer is harmful / unsafe.
- [X] The answer is not correct.
- [X] The answer is not helpful.
- [ ] The answer is outdated.

### What did you ask?

Typescript, i have a class with lots of properties. Write me a template 'toJson' including comments explaining what the parameter 'key' means.

### What did AI Help answer?

First it answered: "I'm sorry, but I can't answer questions outside web development."  Then i said "This is web development", and it responded:

"Certainly! TypeScript, being a superset of JavaScript, allows you to define classes with properties and methods. When you want to convert an instance of a class to a JSON string, you might implement a toJson method within your class."

### What MDN pages did AI Help consult?

It eventually consulted the correct pages.

**Comment by psm384** [comment]
But the original reason I clicked "this is wrong", is because, once confusion over casing is settled, the AI asserts:

"Regarding the key parameter, it's important to note that when toJSON is invoked during the serialization process, it does not receive any arguments."

Even *after* i told it, yes, it does receive parameters. Only when i quote this back and say "this is wrong" do i get a correct answer.

Hope this is helpful. Love this AI guys.,

**Comment by psm384** [comment]
And of course you guys know all this .. but here's sample code showing how 'key' is used in toJSON:

```
class myClass {
  constructor() {
    this.state = 'foo'
  }
  toJSON(key) {
    console.log("Key:", key)
    return { state: 'bar' }
  }
}

z = new myClass()
console.log(JSON.stringify(z)) // key will be empty string
console.log(JSON.stringify({ someObject: z })) // key will be 'someObject'
console.log(JSON.stringify([z, z])) // key will be "0" and "1"

// these variations are amusingly ambiguous:
console.log(JSON.stringify({ 1: z })) // can't be distinguished from index
console.log(JSON.stringify({ "": z })) // can't be distinguished from property name
```

**Comment by caugner** [comment]
Hi @psm384, 👋 

Thank you for reporting this issue, but it looks like you didn't use the "Report a problem with this answer" link or changed the automatically set fields ("Set automatically. Do not modify."), so we cannot act on your report.

Can you please try your question again and use the "Report a problem with this answer" link, only filling out the first two sections ("What is the issue with the answer?" and "How would you categorize this issue?")?

Thank you for your understanding. 🙏

**Comment by psm384** [comment]
it's feedback. you can try to make use of it or not. it's not an "issue". to be blunt, what do i care if you "act" on it or not? i'll just use another AI.

**Comment by HerminaC** [comment]
@psm384 - you're right and thanks for taking the time to send us feedback, we appreciate it and it helps us.
