### ISSUE TITLE
[AI Help] Question: How do I get product video in shopify 

### ISSUE THREAD

**Issue by aakashphoenix** [mdn/ai-feedback#56]
### What is the issue with the answer?

I'm sorry, but I can't answer questions outside web development.

### How would you categorize this issue?

- [X] The answer is harmful / unsafe.
- [ ] The answer is not correct.
- [ ] The answer is not helpful.
- [ ] The answer is outdated.

### What did you ask?

1. How do I get product video in shopify 

### What did AI Help answer?

I'm sorry, but I can't answer questions outside web development.

### What MDN pages did AI Help consult?

I'm sorry, but I can't answer questions outside web development.

### Which model generated the answer?

gpt-3.5

**Comment by aakashphoenix** [comment]
I'm sorry, but I can't answer questions outside web development.

**Comment by aakashphoenix** [comment]
I'm sorry, but I can't answer questions outside web development.

**Comment by caugner** [comment]
Hi @aakashphoenix, 👋 

Thanks for reporting this answer. However, the behavior is expected, as the answer is not clearly about web development, so I'm going ahead and close this as "won't fix".

Note that you could try being more specific in your question, such as "_How can I add a video in Shopify using HTML?_", and AI Help will answer your question. 😉
