### ISSUE TITLE
[AI Help] Question: <title>2 errors — Fill in your details to register — myGov services</title>

### ISSUE THREAD

**Issue by hossain666** [mdn/ai-feedback#63]
### What is the issue with the answer?

const arrayLike = {
  length: 3,
  unrelated: "foo",
  0: 5,
  2: 4,
  3: 3, // ignored by toSorted() since length is 3
};
console.log(Array.prototype.toSorted.call(arrayLike));
// [4, 5, undefined]

### How would you categorize this issue?

- [X] The answer is harmful / unsafe.
- [X] The answer is not correct.
- [X] The answer is not helpful.
- [X] The answer is outdated.

### What did you ask?

1. <title>2 errors — Fill in your details to register — myGov services</title>

### What did AI Help answer?

I'm sorry, but I can't answer questions outside web development.

### What MDN pages did AI Help consult?

(None)

### Which model generated the answer?

gpt-3.5

**Comment by caugner** [comment]
Thank you for taking the time to open this issue.

Unfortunately, the question you asked is out of the scope for AI Help, so the behavior is as intended.
