### ISSUE TITLE
[AI Help] Question: How do I do CSS Nesting?

### ISSUE THREAD

**Issue by AlbertMarashi** [mdn/ai-feedback#8]
### What is the issue with the answer?

Doesn't take into account CSS nesting is now native supported

### How would you categorize this issue?

- [ ] The answer is harmful / unsafe.
- [X] The answer is not correct.
- [ ] The answer is not helpful.

### What did you ask?

1. How do I do CSS Nesting?

### What did AI Help answer?

CSS nesting refers to the ability to write CSS rules that are nested within other CSS rules. This allows you to target specific elements within a parent element and apply styles to them. However, CSS itself does not have native support for nesting. 

To achieve nesting in CSS, you can use a preprocessor like Sass or Less. These preprocessors extend the functionality of CSS and provide features such as nesting. Here is an example of how nesting can be done using Sass:

```scss
.parent {
  color: blue;

  .child {
    font-weight: bold;
  }
}
```

In the above example, the `.child` rule is nested within the `.parent` rule. This means that the styles defined within the `.child` rule will only apply to elements that are descendants of the `.parent` element.

After writing the nested styles in Sass, you need to compile the Sass code into regular CSS using a Sass compiler. The compiled CSS will then contain the nested styles.

It's important to note that if you are using plain CSS without a preprocessor, you cannot directly nest CSS rules. Each rule must be written separately and independently of each other. However, you can use selectors to target specific elements within a parent element. For example:

```css
.parent {
  color: blue;
}

.parent .child {
  font-weight: bold;
}
```

In the above example, the `.child` rule is targeting elements with the class `child` that are descendants of elements with the class `parent`. This achieves a similar effect to nesting, but the styles are not actually nested within each other in the CSS code.

Remember, CSS nesting is not a native feature of CSS itself, but can be achieved using preprocessors like Sass or by using selectors to target specific elements within a parent element.

### What MDN pages did AI Help consult?

- [Cascade, specificity, and inheritance](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance)
- [CSS building blocks](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks)
- [Learn to style HTML using CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS)

**Comment by caugner** [comment]
Thank you for taking the time to report this issue. 👍 

It looks like CSS Nesting is mentioned [on only one MDN page](https://github.com/search?q=repo%3Amdn%2Fcontent%20%22CSS%20nesting%22%20&type=code), which doesn't explain the feature, and this content was not consulted by AI Help.

My assessment is that the issue is caused by a content gap, which has been reported in https://github.com/mdn/mdn/issues/413 and might be addressed by https://github.com/mdn/content/issues/27180.

We will keep this issue open to follow-up once the content has been added.

PS: I added the option "The answer is outdated." to the issue template now.

**Comment by Rajeevjewar** [comment]
You can go for SCSS for nesting in CSS.

**Comment by AlbertMarashi** [comment]
@caugner this looks like its done with https://github.com/mdn/content/issues/27180 so I will close
